# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ---- 1、General Information

title: Tung's Archive
SEOTitle: Xuan Tung Hoang
header-img: img/home-bg.jpg
email: hxtunq@gmail.com
description: "Every failure is leading towards success."
keyword: "biology, astrobiology, science, universe, blog"
url: "http://orionanseaweed.github.io"
baseurl: ""
github_repo: "https://github.com/orionanseaweed/orionanseaweed.github.io.git" 

# ---- 2、Sidebar

sidebar: true
sidebar--description: "Incoming biologist."
sidebar-avatar: /img/Stone-MinecraftWiki.png

# ---- 3、Social Media

RSS: false 

facebook_username:  hxtunq
github_username: orionanseaweed
instagram_username: lemarid_an    
flickr_username:    196824145@N03

# Featured Tags

featured-tags: true               # 
featured-condition-size: 1        # 

# Friends

friends: [
    {
        title: "ABCD",             
        href: "http://abcd.github.io/"  
    }
]

# ---- 4、构建配置

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty   
paginate: 10 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true  # if you want to customize anchor. check out line:181 of `post.html`

# Gems #  The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM   # use Github Flavored Markdown !important

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# ---- 5、插件配置

# Google Analytics
# ga_track_id: 'UA-xxxxxx-xx
# ga_domain: xxxx.top     

